### ISSUE TITLE
webform fix

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/drupal#188]
@ricardfo , duas coisas:

1. Essa flag tem que sair:

```
_core:
  default_config_hash: Ec4va_HZl3RMttAflc8Oh7hFjwddLh1Jo4yTR9e80FE
```
Eu sempre a removo na mão, pois quando formos rodar em todos sites vai quebrar, pois cada site tem seu core hash.

2. Não precisa versionar o arquivo inteiro, só as chaves que nos interessam, no caso acho que são (tem q testar):

```
file:
  file_public: true
html_editor:
  disabled: true
```
https://github.com/fflch/drupal/commit/1eadbacc94aa8fbc1105b7c846411698c38bf211
